apiVersion: apps/v1
kind: Deployment
metadata:
  name: dic-don-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dic-don-game
  template:
    metadata:
      labels:
        app: dic-don-game
    spec:
      imagePullSecrets:
        - name: ghcr-secret  # Ensure the secret is referenced
      containers:
        - name: dic-don-game
          image: ghcr.io/mupparaju19/dic-don:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
