apiVersion: apps/v1
kind: Deployment
metadata:
  name: dic-don-game
  namespace: default  # ✅ Optional: Specify a namespace (change if needed)
  labels:
    app: dic-don-game
  annotations:
    description: "Deployment for dic-don-game application"  # ✅ Optional: Add metadata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dic-don-game
  template:
    metadata:
      labels:
        app: dic-don-game
    spec:
      containers:
        - name: dic-don-game
          image: ghcr.io/mupparaju19/dic-don-game:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 80  # Exposes port 80 on the container
          resources:  # ✅ Add resource limits and requests
            requests:
              memory: "128Mi"
              cpu: "100m"  # 0.1 CPU core
            limits:
              memory: "256Mi"
              cpu: "200m"  # 0.2 CPU core
          livenessProbe:  # ✅ Add liveness probe to check if the app is alive
            httpGet:
              path: /health  # Adjust path based on your app's health endpoint
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:  # ✅ Add readiness probe to check if the app is ready
            httpGet:
              path: /health  # Adjust path based on your app's health endpoint
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: ghcr-secret  # ✅ Kept this for GHCR authentication