apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dic-don-game-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: dic-don-game.local  # Replace with an actual domain if needed
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dic-don-game-service
                port:
                  number: 80  # This matches the Service's `port`
