name: Deploy dic-don-game

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u Mupparaju19 --password-stdin


      - name: Build Docker Image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository }}/dic-don-game:latest .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/dic-don-game:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Kubeconfig Secret
        run: |
          if [ -z "${{ secrets.KUBECONFIG }}" ]; then
            echo "KUBECONFIG secret is missing!"
            exit 1
          fi

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml

      - name: Wait for Deployment to be Ready
        run: kubectl rollout status deployment/dic-don-game

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get ingress
