name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # =============================
  # ✅ Stage 1: Build & Test
  # =============================
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Run Tests (Optional - Add tests to package.json)
        run: echo "No tests available." && exit 0

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist

  # =============================
  # ✅ Stage 2: Build Docker Image
  # =============================
  build-docker:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/tic-tac-toe:latest .
          docker tag ghcr.io/${{ github.repository_owner }}/tic-tac-toe:latest ghcr.io/${{ github.repository_owner }}/tic-tac-toe:${{ github.sha }}

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/tic-tac-toe:latest
          docker push ghcr.io/${{ github.repository_owner }}/tic-tac-toe:${{ github.sha }}

  # =============================
  # ✅ Stage 3: Deploy to Kubernetes (Optional)
  # =============================
  deploy:
    needs: build-docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/tic-tac-toe tic-tac-toe=ghcr.io/${{ github.repository_owner }}/tic-tac-toe:latest
          kubectl rollout status deployment/tic-tac-toe
